### PR TITLE
ZnBufferedReadStream>>upToEnd performance

### PR DESCRIPTION
**Pull request by akgrant43**
ZnBufferedReadStream>>upToEnd currently retrieves buffers from the underlying stream and then writes them to a WriteStream, which grows its buffer in steps. For a 4M file approximately 15 buffers (ByteArray | String) of increasing size will be created, copied and discarded.

Since many streams know their size, #upToEnd can create and load a single buffer by using next: size - position. This automatically handles cases where size is an over-estimate, and a check can be made afterwards in case size is an under-estimate.

A 4Mbyte file on my Dell XPS13 loads approx. 6 times faster with this optimisation.

Fixes: https://github.com/pharo-project/pharo/issues/3135

### CODE REVIEW

**Comment by akgrant43** [comment]
Iceberg renamed skipWhiteSpace..st to skipWhitespace..st.  The file name looks wrong to me in https://github.com/svenvc/zinc/blob/master/repository/Zinc-Character-Encoding-Core.package/ZnBase64Encoder.class/instance/skipWhiteSpace..st but let me know if this needs changing.

Ready for review / merge.

Thanks!
Alistair

**Comment by svenvc** [comment]
Hi,

I know you are working on fast reading of files, and yes, #upToEnd can be much more efficient if you know the size upfront. So I agree with the change.

But I was wondering how often does a real under-estimate happen ? I figure the zero case happens more often.

I would guess that in the under-estimate case, the situation is like 4MB read, 1K left ? If so, I think it would be more efficient to pull the #nextPutAll: of the 4MB result out of the #streamContents: and do a real concatenation with #, at the end. This is because the growing behavior of #streamContents: is costly, especially for large collections.

Stylistically, I would also prefer a direct reference to position instead of an accessor.

What do you think ?

Sven

**Comment by akgrant43** [comment]
Hi Sven,

> I know you are working on fast reading of files, and yes, #upToEnd can be much more efficient if you know the size upfront. So I agree with the change.
> 
> But I was wondering how often does a real under-estimate happen ? I figure the zero case happens more often.

I agree that correct or 0 size are the two most common cases.  I was assuming that an under- or over-estimate would be the exception, but it still has to be handled correctly.


> I would guess that in the under-estimate case, the situation is like 4MB read, 1K left ? If so, I think it would be more efficient to pull the #nextPutAll: of the 4MB result out of the #streamContents: and do a real concatenation with #, at the end. This is because the growing behavior of #streamContents: is costly, especially for large collections.

Agreed, I've updated the PR as you suggest.


> Stylistically, I would also prefer a direct reference to position instead of an accessor.

Would this be valid?  The stream position is "stream position - limit + position - 1", so just using the position variable would be incorrect because it is relative to the ZnBufferedReadStream buffer, right?

Having a variable called 'position' in this case is somewhat misleading since the accessor #position is referring to a different concept.


Thanks for your suggestions!

Cheers,
Alistair

**Comment by svenvc** [comment]
You're right about #position - it is confusing, duh.

**Comment by akgrant43** [comment]
Thanks, Sven!

**Pull request merged**
