### PR TITLE
prepare integration into Pharo 10

### PR DESCRIPTION
**Pull request by demarey**
add a test.
avoid strong reference to 'Graphics-Files' package

### CODE REVIEW

**Comment by svenvc** [comment]
This is cheating but maybe for now this is OK as we can try to fix it later on.

I looked again at the users of ZnEasy and I more strongly believe it should be moved away from core Zinc-HTTP, I can easily fix all system users.

Furthermore, from a design perspective I never liked it, it is too simple and should not be used in production code.

It would fit better in Examples (since that already exists).

**Comment by demarey** [comment]
> This is cheating but maybe for now this is OK as we can try to fix it later on.

Indeed. As `#getImageOfType:fromUrl:` is probably never used when `Graphics-Files` is not loaded, it is a fast way to be able to load Zinc code from its own repository.

> I looked again at the users of ZnEasy and I more strongly believe it should be moved away from core Zinc-HTTP, I can easily fix all system users.
> 
> Furthermore, from a design perspective I never liked it, it is too simple and should not be used in production code.
> 
> It would fit better in Examples (since that already exists).

Yes, it could be a good idea. But no need to rush for it.

**Comment by svenvc** [comment]
So I assume I should merge this ?

**Comment by demarey** [comment]
Yes, I think it can be merged.
We could add an issue on how to solve better the `#getImageOfType:fromUrl:`dependency problem.

**Pull request merged**
