### PR TITLE
Centralize JSON parser choice in ZnUtils

### PR DESCRIPTION
**Pull request by labordep**
This is now possible to load Zinc OAuth2 package directly from the package and to use it with the Pharo STONJSON parser.
+ Unit test
+ minor fixes
+ adding .gittatribute file to manage End of file encoding between Windows and others OS

### CODE REVIEW

**Comment by labordep** [comment]
Hi @svenvc, sorry for adding the .gitattribute file but this is the only way for me to contribute without encoding problems from my Windows PC. Delete it after if you want.

**Comment by svenvc** [comment]
Hi,

This looks good to me, I will integrate it next week.

Thx,

Sven

**Comment by labordep** [comment]
Hi @svenvc, I'm using your OAuth2 stuff for desktop-app is this is working fine ! I have do a litte  fix (see my PR) but nothing important :)

**Comment by svenvc** [comment]
Thank you!

**Pull request merged**
