### PR TITLE
Condense sources before the next Pharo sync

### PR DESCRIPTION
**Pull request by jecisc**

### CODE REVIEW

**Comment by svenvc** [comment]
How sure are you nothing got overwritten ?

Or did you run this after you loaded Zinc again ?

**Comment by jecisc** [comment]
I loaded Zinc then applied the script. And now I’m checking manually the changes in the "files changed" tab. It just takes time for 3000+ line changed @w@

**Comment by svenvc** [comment]
If you really started after a successful load of the latest Zinc from its repo, there is no real need to check everything manually.

I did the same for Zodiac and STON already.

Shall I merge then ?

**Comment by jecisc** [comment]
The CI is green so I think we can :)

**Comment by svenvc** [comment]
Done, thanks!

**Pull request merged**
