### PR TITLE
Sync with Pharo

### PR DESCRIPTION
**Pull request by jecisc**
- Rename test case to end with "Test" and follow Pharo conventions
- Remove testGetPharoVersion
- Remove some dead code 
- Increase number of redirect possible for gmail test

### CODE REVIEW

**Comment by svenvc** [comment]
Are you sure everything that you intended got included ?

testGetPharoVersion seems to fail, hence it was not removed.

**Comment by jecisc** [comment]
I’ve seen that but I don’t see it added in my PR. Just removed 
5D916FA5-F1E8-4676-A292-0E9240357DA0

I’ll check again when I’ll be on my computer

**Comment by jecisc** [comment]
Could it be that Pharo8 has a failing version of the test, and since this version does not add this method anymore, it does not crush the old test?

**Comment by svenvc** [comment]
OK, I will merge and see what happens

**Comment by svenvc** [comment]
Grrrr, this is really annoying, it works on my machine (pharo 11), I will have a look later on

**Comment by svenvc** [comment]
I fixed it as follows: https://github.com/svenvc/zinc/commit/a77011cbf89e130495272cac46c8cda29ba4d1bf

**Pull request merged**
